name: Laravel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deployment
      uses: appleboy/ssh-action@master
      with: 
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        script: |
          cd apps/ror-php
          git checkout -f
          git pull
