name: Sample
on:
  workflow_dispatch:
    branches: [main]

env:
  FIRST_NAME: Mona
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
        SSH_KEY: ${{secrets.SSH_KEY}}
        SERVER_IP: ${{secrets.SERVER_IP}}
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: actions/checkout@master
        run: bash deploy.sh