name: Sample
on:
  workflow_dispatch:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
        SSH_KEY: ${{secrets.SSH_KEY}}
        SERVER_IP: ${{secrets.SERVER_IP}}
    steps:
      - uses: actions/checkout@master
      - run: bash deploy.sh